# Generated by Django 3.2 on 2023-08-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
